-- Option 1: If you want to rename the existing column (preserves data)
ALTER TABLE testimonials 
RENAME COLUMN email TO designation;

-- Option 2: If you've already created a new column and want to migrate data
-- This assumes both columns exist temporarily
-- UPDATE testimonials 
-- SET designation = email 
-- WHERE designation IS NULL AND email IS NOT NULL;

-- Option 3: If you need to drop the old column and create a new one
-- ALTER TABLE testimonials DROP COLUMN email;
-- ALTER TABLE testimonials ADD COLUMN designation TEXT NOT NULL;

-- Option 4: If you're creating the table from scratch
-- CREATE TABLE testimonials (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name TEXT NOT NULL,
--   designation TEXT NOT NULL,
--   company TEXT,
--   testimonial TEXT NOT NULL,
--   approved BOOLEAN DEFAULT FALSE,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );